import { db } from '@/db';
import { menuItems } from '@/db/schema';

async function main() {
    const sampleMenuItems = [
        // Jollof Kitchen (restaurantId: 1) - 5 items
        {
            restaurantId: 1,
            name: 'Jollof Rice with Chicken',
            slug: 'jollof-rice-with-chicken',
            description: 'Our signature West African jollof rice cooked in rich tomato sauce, served with grilled chicken and fried plantain.',
            price: 250000,
            originalPrice: 300000,
            imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '20 min',
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            restaurantId: 1,
            name: 'Nigerian Fried Rice',
            slug: 'nigerian-fried-rice',
            description: 'Flavorful fried rice with mixed vegetables, liver, and shrimp. A party favorite!',
            price: 220000,
            imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Chef\'s Special',
            preparationTime: '18 min',
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            restaurantId: 1,
            name: 'Beef Suya',
            slug: 'beef-suya',
            description: 'Spicy grilled beef skewers marinated in authentic Nigerian suya spice blend.',
            price: 180000,
            imageUrl: 'https://images.unsplash.com/photo-1529042410759-befb1204b468?w=600&h=600&fit=crop',
            category: 'Appetizers',
            isAvailable: 1,
            badge: 'Spicy',
            preparationTime: '15 min',
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            restaurantId: 1,
            name: 'Pepper Soup',
            slug: 'pepper-soup',
            description: 'Traditional Nigerian hot and spicy soup with goat meat and aromatic spices.',
            price: 150000,
            imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Spicy',
            preparationTime: '25 min',
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            restaurantId: 1,
            name: 'Fried Plantain',
            slug: 'fried-plantain',
            description: 'Sweet and crispy fried ripe plantain slices, perfect as a side or snack.',
            price: 80000,
            imageUrl: 'https://images.unsplash.com/photo-1606923829579-0cb981a83e2e?w=600&h=600&fit=crop',
            category: 'Sides',
            isAvailable: 1,
            badge: null,
            preparationTime: '10 min',
            createdAt: new Date('2024-01-20').toISOString(),
        },

        // Dragon Wok (restaurantId: 2) - 4 items
        {
            restaurantId: 2,
            name: 'Special Fried Rice',
            slug: 'special-fried-rice',
            description: 'Chinese-style fried rice with egg, vegetables, and choice of chicken or shrimp.',
            price: 280000,
            imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '15 min',
            createdAt: new Date('2024-01-11').toISOString(),
        },
        {
            restaurantId: 2,
            name: 'Sweet & Sour Chicken',
            slug: 'sweet-sour-chicken',
            description: 'Crispy chicken pieces in tangy sweet and sour sauce with bell peppers and pineapple.',
            price: 320000,
            originalPrice: 380000,
            imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Chef\'s Special',
            preparationTime: '20 min',
            createdAt: new Date('2024-01-13').toISOString(),
        },
        {
            restaurantId: 2,
            name: 'Vegetable Spring Rolls',
            slug: 'vegetable-spring-rolls',
            description: 'Crispy deep-fried rolls filled with fresh vegetables and glass noodles.',
            price: 120000,
            imageUrl: 'https://images.unsplash.com/photo-1605525742036-c5ad05f0bc55?w=600&h=600&fit=crop',
            category: 'Appetizers',
            isAvailable: 1,
            badge: 'New',
            preparationTime: '12 min',
            createdAt: new Date('2024-02-01').toISOString(),
        },
        {
            restaurantId: 2,
            name: 'Chicken Chow Mein',
            slug: 'chicken-chow-mein',
            description: 'Stir-fried noodles with chicken, vegetables and savory sauce.',
            price: 300000,
            imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '18 min',
            createdAt: new Date('2024-01-16').toISOString(),
        },

        // Pizza Paradise (restaurantId: 3) - 5 items
        {
            restaurantId: 3,
            name: 'Margherita Pizza',
            slug: 'margherita-pizza',
            description: 'Classic Italian pizza with fresh mozzarella, tomato sauce, and basil.',
            price: 350000,
            imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '20 min',
            createdAt: new Date('2024-01-09').toISOString(),
        },
        {
            restaurantId: 3,
            name: 'Pepperoni Pizza',
            slug: 'pepperoni-pizza',
            description: 'Loaded with mozzarella cheese and generous pepperoni slices on crispy crust.',
            price: 420000,
            originalPrice: 480000,
            imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Chef\'s Special',
            preparationTime: '22 min',
            createdAt: new Date('2024-01-14').toISOString(),
        },
        {
            restaurantId: 3,
            name: 'BBQ Chicken Pizza',
            slug: 'bbq-chicken-pizza',
            description: 'Grilled chicken with BBQ sauce, onions, and cheese on hand-tossed dough.',
            price: 450000,
            imageUrl: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '23 min',
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            restaurantId: 3,
            name: 'Garlic Bread',
            slug: 'garlic-bread',
            description: 'Toasted bread with butter, garlic, and parsley. Perfect side for any pizza.',
            price: 100000,
            imageUrl: 'https://images.unsplash.com/photo-1573140401552-3fab0b24306f?w=600&h=600&fit=crop',
            category: 'Sides',
            isAvailable: 1,
            badge: null,
            preparationTime: '10 min',
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            restaurantId: 3,
            name: 'Caesar Salad',
            slug: 'caesar-salad',
            description: 'Crisp romaine lettuce with Caesar dressing, croutons, and parmesan cheese.',
            price: 180000,
            imageUrl: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=600&h=600&fit=crop',
            category: 'Sides',
            isAvailable: 1,
            badge: 'New',
            preparationTime: '10 min',
            createdAt: new Date('2024-02-03').toISOString(),
        },

        // Burger Hub (restaurantId: 4) - 5 items
        {
            restaurantId: 4,
            name: 'Classic Beef Burger',
            slug: 'classic-beef-burger',
            description: 'Juicy beef patty with lettuce, tomato, onions, pickles, and special sauce.',
            price: 280000,
            imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '15 min',
            createdAt: new Date('2024-01-08').toISOString(),
        },
        {
            restaurantId: 4,
            name: 'Double Cheese Burger',
            slug: 'double-cheese-burger',
            description: 'Two beef patties with double cheese, caramelized onions, and burger sauce.',
            price: 380000,
            originalPrice: 420000,
            imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Chef\'s Special',
            preparationTime: '18 min',
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            restaurantId: 4,
            name: 'Crispy Chicken Burger',
            slug: 'crispy-chicken-burger',
            description: 'Fried chicken breast with coleslaw, mayo, and pickles in a soft bun.',
            price: 320000,
            imageUrl: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '16 min',
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            restaurantId: 4,
            name: 'French Fries',
            slug: 'french-fries',
            description: 'Golden crispy fries seasoned with salt. Add cheese or chili for extra.',
            price: 90000,
            imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f390859f?w=600&h=600&fit=crop',
            category: 'Sides',
            isAvailable: 1,
            badge: null,
            preparationTime: '10 min',
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            restaurantId: 4,
            name: 'Chocolate Milkshake',
            slug: 'chocolate-milkshake',
            description: 'Thick and creamy chocolate milkshake topped with whipped cream.',
            price: 150000,
            imageUrl: 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=600&h=600&fit=crop',
            category: 'Drinks',
            isAvailable: 1,
            badge: 'New',
            preparationTime: '8 min',
            createdAt: new Date('2024-02-05').toISOString(),
        },

        // Amala Spot (restaurantId: 5) - 4 items
        {
            restaurantId: 5,
            name: 'Amala & Ewedu with Assorted',
            slug: 'amala-ewedu-assorted',
            description: 'Traditional Yoruba amala served with ewedu soup and assorted meat.',
            price: 280000,
            imageUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '20 min',
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            restaurantId: 5,
            name: 'Pounded Yam & Egusi',
            slug: 'pounded-yam-egusi',
            description: 'Smooth pounded yam with rich egusi soup and fish or meat.',
            price: 320000,
            imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Chef\'s Special',
            preparationTime: '25 min',
            createdAt: new Date('2024-01-13').toISOString(),
        },
        {
            restaurantId: 5,
            name: 'Eba & Egusi Soup',
            slug: 'eba-egusi-soup',
            description: 'Garri eba with melon seed soup, loaded with fish and meat.',
            price: 250000,
            imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Spicy',
            preparationTime: '20 min',
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            restaurantId: 5,
            name: 'Ofada Rice & Sauce',
            slug: 'ofada-rice-sauce',
            description: 'Local unpolished rice with spicy ofada stew and fried plantain.',
            price: 300000,
            originalPrice: 350000,
            imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Spicy',
            preparationTime: '22 min',
            createdAt: new Date('2024-01-19').toISOString(),
        },

        // Sushi Delight (restaurantId: 6) - 4 items
        {
            restaurantId: 6,
            name: 'California Roll',
            slug: 'california-roll',
            description: 'Classic sushi roll with crab stick, avocado, and cucumber.',
            price: 450000,
            imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '15 min',
            createdAt: new Date('2024-01-11').toISOString(),
        },
        {
            restaurantId: 6,
            name: 'Salmon Sashimi',
            slug: 'salmon-sashimi',
            description: 'Fresh sliced salmon served with wasabi and soy sauce.',
            price: 550000,
            imageUrl: 'https://images.unsplash.com/photo-1564489563601-c53cfc451e93?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Chef\'s Special',
            preparationTime: '12 min',
            createdAt: new Date('2024-01-14').toISOString(),
        },
        {
            restaurantId: 6,
            name: 'Tempura Roll',
            slug: 'tempura-roll',
            description: 'Crispy shrimp tempura with avocado and spicy mayo.',
            price: 480000,
            imageUrl: 'https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'New',
            preparationTime: '18 min',
            createdAt: new Date('2024-02-02').toISOString(),
        },
        {
            restaurantId: 6,
            name: 'Miso Soup',
            slug: 'miso-soup',
            description: 'Traditional Japanese soup with tofu, seaweed, and green onions.',
            price: 120000,
            imageUrl: 'https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=600&h=600&fit=crop',
            category: 'Drinks',
            isAvailable: 1,
            badge: null,
            preparationTime: '10 min',
            createdAt: new Date('2024-01-17').toISOString(),
        },

        // Spice Route (restaurantId: 7) - 4 items
        {
            restaurantId: 7,
            name: 'Chicken Tikka Masala',
            slug: 'chicken-tikka-masala',
            description: 'Tender chicken in creamy tomato curry sauce with aromatic spices.',
            price: 380000,
            imageUrl: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Spicy',
            preparationTime: '22 min',
            createdAt: new Date('2024-01-09').toISOString(),
        },
        {
            restaurantId: 7,
            name: 'Chicken Biryani',
            slug: 'chicken-biryani',
            description: 'Fragrant basmati rice cooked with spiced chicken and herbs.',
            price: 420000,
            originalPrice: 480000,
            imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '25 min',
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            restaurantId: 7,
            name: 'Garlic Naan Bread',
            slug: 'garlic-naan-bread',
            description: 'Soft Indian flatbread brushed with garlic butter.',
            price: 100000,
            imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&h=600&fit=crop',
            category: 'Sides',
            isAvailable: 1,
            badge: null,
            preparationTime: '12 min',
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            restaurantId: 7,
            name: 'Vegetable Samosas',
            slug: 'vegetable-samosas',
            description: 'Crispy pastry filled with spiced potatoes and peas.',
            price: 130000,
            imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=600&h=600&fit=crop',
            category: 'Appetizers',
            isAvailable: 1,
            badge: 'Spicy',
            preparationTime: '10 min',
            createdAt: new Date('2024-01-18').toISOString(),
        },

        // Fried Chicken Express (restaurantId: 8) - 4 items
        {
            restaurantId: 8,
            name: 'Fried Chicken (4 Pieces)',
            slug: 'fried-chicken-4-pieces',
            description: 'Crispy golden fried chicken with our special blend of herbs and spices.',
            price: 320000,
            imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '18 min',
            createdAt: new Date('2024-01-08').toISOString(),
        },
        {
            restaurantId: 8,
            name: 'Spicy Chicken Wings',
            slug: 'spicy-chicken-wings',
            description: 'Hot and spicy chicken wings tossed in buffalo sauce.',
            price: 280000,
            imageUrl: 'https://images.unsplash.com/photo-1608039755401-742074f0548d?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Spicy',
            preparationTime: '16 min',
            createdAt: new Date('2024-01-11').toISOString(),
        },
        {
            restaurantId: 8,
            name: 'Coleslaw',
            slug: 'coleslaw',
            description: 'Fresh cabbage and carrot salad with creamy dressing.',
            price: 80000,
            imageUrl: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=600&h=600&fit=crop',
            category: 'Sides',
            isAvailable: 1,
            badge: null,
            preparationTime: '8 min',
            createdAt: new Date('2024-01-14').toISOString(),
        },
        {
            restaurantId: 8,
            name: 'Soft Drink',
            slug: 'soft-drink',
            description: 'Chilled soft drink - choice of Coke, Sprite, or Fanta.',
            price: 50000,
            imageUrl: 'https://images.unsplash.com/photo-1581006852262-e4307cf6283a?w=600&h=600&fit=crop',
            category: 'Drinks',
            isAvailable: 1,
            badge: null,
            preparationTime: '5 min',
            createdAt: new Date('2024-01-17').toISOString(),
        },

        // Mama's Kitchen (restaurantId: 9) - 5 items
        {
            restaurantId: 9,
            name: 'Afang Soup',
            slug: 'afang-soup',
            description: 'Nutritious vegetable soup with waterleaf, periwinkle, and assorted meat.',
            price: 300000,
            imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Chef\'s Special',
            preparationTime: '23 min',
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            restaurantId: 9,
            name: 'Rice & Stew',
            slug: 'rice-stew',
            description: 'White rice with rich tomato stew and choice of chicken or fish.',
            price: 220000,
            imageUrl: 'https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '18 min',
            createdAt: new Date('2024-01-13').toISOString(),
        },
        {
            restaurantId: 9,
            name: 'Fried Fish',
            slug: 'fried-fish',
            description: 'Crispy fried tilapia or catfish seasoned with Nigerian spices.',
            price: 200000,
            imageUrl: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '15 min',
            createdAt: new Date('2024-01-16').toISOString(),
        },
        {
            restaurantId: 9,
            name: 'Moi Moi',
            slug: 'moi-moi',
            description: 'Steamed bean pudding made from blended black-eyed peas.',
            price: 120000,
            imageUrl: 'https://images.unsplash.com/photo-1626200418118-2a3cc9e6d3db?w=600&h=600&fit=crop',
            category: 'Sides',
            isAvailable: 1,
            badge: null,
            preparationTime: '20 min',
            createdAt: new Date('2024-01-19').toISOString(),
        },
        {
            restaurantId: 9,
            name: 'Fresh Fruit Salad',
            slug: 'fresh-fruit-salad',
            description: 'Mix of fresh tropical fruits - pineapple, watermelon, and banana.',
            price: 150000,
            imageUrl: 'https://images.unsplash.com/photo-1564093497595-593b96d80180?w=600&h=600&fit=crop',
            category: 'Sides',
            isAvailable: 1,
            badge: 'New',
            preparationTime: '10 min',
            createdAt: new Date('2024-02-04').toISOString(),
        },

        // Shawarma Palace (restaurantId: 10) - 4 items
        {
            restaurantId: 10,
            name: 'Chicken Shawarma',
            slug: 'chicken-shawarma',
            description: 'Grilled chicken wrapped in pita with vegetables and garlic sauce.',
            price: 180000,
            imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '12 min',
            createdAt: new Date('2024-01-09').toISOString(),
        },
        {
            restaurantId: 10,
            name: 'Beef Shawarma',
            slug: 'beef-shawarma',
            description: 'Tender beef shawarma with tahini sauce and fresh vegetables.',
            price: 200000,
            originalPrice: 250000,
            imageUrl: 'https://images.unsplash.com/photo-1628158454618-37e88e09ff18?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '13 min',
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            restaurantId: 10,
            name: 'Falafel Wrap',
            slug: 'falafel-wrap',
            description: 'Crispy chickpea falafel with hummus, tahini, and salad in pita.',
            price: 160000,
            imageUrl: 'https://images.unsplash.com/photo-1593699375628-2ccf769f9615?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'New',
            preparationTime: '11 min',
            createdAt: new Date('2024-02-01').toISOString(),
        },
        {
            restaurantId: 10,
            name: 'Hummus with Pita',
            slug: 'hummus-pita',
            description: 'Creamy chickpea hummus served with warm pita bread.',
            price: 110000,
            imageUrl: 'https://images.unsplash.com/photo-1621832360365-28b6e5da1e09?w=600&h=600&fit=crop',
            category: 'Appetizers',
            isAvailable: 1,
            badge: null,
            preparationTime: '8 min',
            createdAt: new Date('2024-01-15').toISOString(),
        },

        // Seafood Bay (restaurantId: 11) - 4 items
        {
            restaurantId: 11,
            name: 'Grilled Fish',
            slug: 'grilled-fish',
            description: 'Fresh whole fish grilled to perfection with lemon butter sauce.',
            price: 500000,
            imageUrl: 'https://images.unsplash.com/photo-1534604973900-c43ab4c2e0ab?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Chef\'s Special',
            preparationTime: '20 min',
            createdAt: new Date('2024-01-11').toISOString(),
        },
        {
            restaurantId: 11,
            name: 'Garlic Butter Prawns',
            slug: 'garlic-butter-prawns',
            description: 'Jumbo prawns sautéed in garlic butter with herbs.',
            price: 600000,
            originalPrice: 700000,
            imageUrl: 'https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '18 min',
            createdAt: new Date('2024-01-14').toISOString(),
        },
        {
            restaurantId: 11,
            name: 'Crispy Calamari',
            slug: 'crispy-calamari',
            description: 'Tender squid rings lightly battered and fried, served with aioli.',
            price: 450000,
            imageUrl: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=600&h=600&fit=crop',
            category: 'Appetizers',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '15 min',
            createdAt: new Date('2024-01-17').toISOString(),
        },
        {
            restaurantId: 11,
            name: 'Seafood Pasta',
            slug: 'seafood-pasta',
            description: 'Linguine with shrimp, mussels, and calamari in tomato sauce.',
            price: 550000,
            imageUrl: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Chef\'s Special',
            preparationTime: '22 min',
            createdAt: new Date('2024-01-20').toISOString(),
        },

        // Vegan Vibes (restaurantId: 12) - 4 items
        {
            restaurantId: 12,
            name: 'Buddha Bowl',
            slug: 'buddha-bowl',
            description: 'Colorful bowl with quinoa, roasted vegetables, chickpeas, and tahini.',
            price: 350000,
            imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Popular',
            preparationTime: '16 min',
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            restaurantId: 12,
            name: 'Quinoa Salad',
            slug: 'quinoa-salad',
            description: 'Protein-rich quinoa with fresh vegetables, avocado, and lemon dressing.',
            price: 300000,
            imageUrl: 'https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'New',
            preparationTime: '14 min',
            createdAt: new Date('2024-02-06').toISOString(),
        },
        {
            restaurantId: 12,
            name: 'Veggie Burger',
            slug: 'veggie-burger',
            description: 'Plant-based patty with lettuce, tomato, avocado, and vegan mayo.',
            price: 280000,
            imageUrl: 'https://images.unsplash.com/photo-1520072959219-c595dc870360?w=600&h=600&fit=crop',
            category: 'Main Course',
            isAvailable: 1,
            badge: 'Chef\'s Special',
            preparationTime: '15 min',
            createdAt: new Date('2024-01-13').toISOString(),
        },
        {
            restaurantId: 12,
            name: 'Acai Smoothie Bowl',
            slug: 'acai-smoothie-bowl',
            description: 'Acai berry smoothie topped with granola, banana, and coconut.',
            price: 250000,
            imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600&h=600&fit=crop',
            category: 'Drinks',
            isAvailable: 1,
            badge: 'New',
            preparationTime: '10 min',
            createdAt: new Date('2024-02-07').toISOString(),
        },
    ];

    await db.insert(menuItems).values(sampleMenuItems);
    
    console.log('✅ Menu items seeder completed successfully - 52 items created');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});