import { db } from '@/db';
import { products } from '@/db/schema';

async function main() {
    const sampleProducts = [
        // Electronics (categoryId: 1) - 4 products
        {
            categoryId: 1,
            name: 'Wireless Bluetooth Headphones',
            slug: 'wireless-bluetooth-headphones',
            description: 'Premium wireless headphones with active noise cancellation and 30-hour battery life. Perfect for studying in noisy environments or enjoying your favorite music between classes.',
            price: 25000,
            originalPrice: 35000,
            imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&h=500&fit=crop',
            badge: 'Best Seller',
            rating: 4.8,
            reviewCount: 245,
            stockQuantity: 45,
            isActive: true,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            categoryId: 1,
            name: 'USB-C Charging Cable 3-Pack',
            slug: 'usb-c-charging-cable-3-pack',
            description: 'Durable fast-charging cables compatible with all USB-C devices. Keep one in your bag, dorm room, and library study spot for convenient charging anywhere on campus.',
            price: 3500,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=500&h=500&fit=crop',
            badge: 'Best Value',
            rating: 4.6,
            reviewCount: 189,
            stockQuantity: 78,
            isActive: true,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            categoryId: 1,
            name: 'Laptop Cooling Pad',
            slug: 'laptop-cooling-pad',
            description: 'Adjustable cooling pad with dual fans to prevent your laptop from overheating during long study sessions. Features ergonomic design and USB-powered operation.',
            price: 15000,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1625948515291-69613efd103f?w=500&h=500&fit=crop',
            badge: 'Trending',
            rating: 4.7,
            reviewCount: 156,
            stockQuantity: 32,
            isActive: true,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            categoryId: 1,
            name: 'Portable Power Bank 20000mAh',
            slug: 'portable-power-bank-20000mah',
            description: 'High-capacity power bank that can charge your phone multiple times. Essential for long days on campus when you need to stay connected for classes and group projects.',
            price: 18000,
            originalPrice: 22000,
            imageUrl: 'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=500&h=500&fit=crop',
            badge: null,
            rating: 4.5,
            reviewCount: 198,
            stockQuantity: 56,
            isActive: true,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },

        // Fashion (categoryId: 2) - 3 products
        {
            categoryId: 2,
            name: 'Classic Canvas Backpack',
            slug: 'classic-canvas-backpack',
            description: 'Spacious and durable backpack with laptop compartment and multiple pockets. Stylish design that fits all your textbooks, laptop, and daily essentials comfortably.',
            price: 12000,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500&h=500&fit=crop',
            badge: 'Best Seller',
            rating: 4.9,
            reviewCount: 287,
            stockQuantity: 67,
            isActive: true,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            categoryId: 2,
            name: 'Cotton T-Shirt 3-Pack',
            slug: 'cotton-t-shirt-3-pack',
            description: 'Comfortable everyday basics in classic colors. Made from soft, breathable cotton that keeps you comfortable through lectures, labs, and late-night study sessions.',
            price: 8500,
            originalPrice: 12000,
            imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&h=500&fit=crop',
            badge: 'Best Value',
            rating: 4.4,
            reviewCount: 142,
            stockQuantity: 89,
            isActive: true,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            categoryId: 2,
            name: 'Comfortable Sneakers',
            slug: 'comfortable-sneakers',
            description: 'Versatile sneakers perfect for walking around campus all day. Cushioned sole provides excellent support for students constantly on the move between classes.',
            price: 28000,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500&h=500&fit=crop',
            badge: 'Trending',
            rating: 4.7,
            reviewCount: 213,
            stockQuantity: 41,
            isActive: true,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },

        // Books & Supplies (categoryId: 3) - 4 products
        {
            categoryId: 3,
            name: 'Scientific Calculator',
            slug: 'scientific-calculator',
            description: 'Advanced calculator approved for exams with over 400 functions. Essential tool for math, physics, engineering, and statistics courses.',
            price: 8000,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1611348524140-53c9a25263d6?w=500&h=500&fit=crop',
            badge: 'Best Seller',
            rating: 4.8,
            reviewCount: 276,
            stockQuantity: 52,
            isActive: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            categoryId: 3,
            name: 'Premium Notebook Set (5-Pack)',
            slug: 'premium-notebook-set-5-pack',
            description: 'High-quality notebooks with thick paper that prevents bleed-through. Perfect for taking detailed lecture notes across all your courses this semester.',
            price: 4500,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=500&h=500&fit=crop',
            badge: 'Best Value',
            rating: 4.6,
            reviewCount: 167,
            stockQuantity: 94,
            isActive: true,
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            categoryId: 3,
            name: 'Highlighter & Pen Combo Pack',
            slug: 'highlighter-pen-combo-pack',
            description: 'Essential writing tools in assorted colors for effective note-taking and textbook studying. Includes both fine-tip pens and broad highlighters.',
            price: 2500,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1586281380349-632531db7ed4?w=500&h=500&fit=crop',
            badge: null,
            rating: 4.5,
            reviewCount: 134,
            stockQuantity: 76,
            isActive: true,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            categoryId: 3,
            name: 'Study Desk Organizer',
            slug: 'study-desk-organizer',
            description: 'Keep your study space tidy with this multi-compartment organizer. Holds pens, sticky notes, paper clips, and other small supplies within easy reach.',
            price: 6000,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1588516903720-8ceb67f9ef84?w=500&h=500&fit=crop',
            badge: 'New Arrival',
            rating: 4.7,
            reviewCount: 98,
            stockQuantity: 38,
            isActive: true,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },

        // Home & Living (categoryId: 4) - 3 products
        {
            categoryId: 4,
            name: 'LED Desk Lamp with USB Port',
            slug: 'led-desk-lamp-usb-port',
            description: 'Adjustable brightness desk lamp with built-in USB charging port. Energy-efficient LED provides perfect lighting for late-night study sessions without straining your eyes.',
            price: 9500,
            originalPrice: 13000,
            imageUrl: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=500&h=500&fit=crop',
            badge: 'Top Rated',
            rating: 4.9,
            reviewCount: 234,
            stockQuantity: 29,
            isActive: true,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            categoryId: 4,
            name: 'Storage Box Set (3-Piece)',
            slug: 'storage-box-set-3-piece',
            description: 'Stackable storage boxes perfect for organizing dorm rooms or small apartments. Keep clothes, books, and supplies neatly stored and easily accessible.',
            price: 7000,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=500&h=500&fit=crop',
            badge: 'Best Value',
            rating: 4.6,
            reviewCount: 178,
            stockQuantity: 55,
            isActive: true,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            categoryId: 4,
            name: 'Mini Fridge for Dorm',
            slug: 'mini-fridge-for-dorm',
            description: 'Compact refrigerator ideal for dorm rooms and small spaces. Keep drinks cold and snacks fresh for convenient access during study breaks.',
            price: 45000,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=500&h=500&fit=crop',
            badge: 'Trending',
            rating: 4.8,
            reviewCount: 156,
            stockQuantity: 18,
            isActive: true,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },

        // Sports & Fitness (categoryId: 5) - 3 products
        {
            categoryId: 5,
            name: 'Yoga Mat with Carry Bag',
            slug: 'yoga-mat-carry-bag',
            description: 'Non-slip exercise mat perfect for yoga, stretching, and workouts in your dorm or campus gym. Lightweight with convenient carrying strap for easy transport.',
            price: 8500,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500&h=500&fit=crop',
            badge: null,
            rating: 4.6,
            reviewCount: 142,
            stockQuantity: 47,
            isActive: true,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            categoryId: 5,
            name: 'Water Bottle 1L',
            slug: 'water-bottle-1l',
            description: 'Durable BPA-free water bottle that keeps you hydrated throughout the day. Wide mouth for easy filling and cleaning, perfect for carrying around campus.',
            price: 3000,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&h=500&fit=crop',
            badge: 'Best Seller',
            rating: 4.7,
            reviewCount: 291,
            stockQuantity: 82,
            isActive: true,
            createdAt: new Date('2024-01-11').toISOString(),
            updatedAt: new Date('2024-01-11').toISOString(),
        },
        {
            categoryId: 5,
            name: 'Resistance Bands Set',
            slug: 'resistance-bands-set',
            description: 'Versatile resistance bands in multiple strength levels for effective workouts anywhere. Ideal for students who want to stay fit without expensive gym memberships.',
            price: 6500,
            originalPrice: 9000,
            imageUrl: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=500&h=500&fit=crop',
            badge: 'Best Value',
            rating: 4.5,
            reviewCount: 128,
            stockQuantity: 61,
            isActive: true,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },

        // Beauty & Health (categoryId: 6) - 2 products
        {
            categoryId: 6,
            name: 'Skincare Gift Set',
            slug: 'skincare-gift-set',
            description: 'Complete skincare routine in travel-friendly sizes. Includes cleanser, toner, moisturizer, and sunscreen to keep your skin healthy despite busy student lifestyle.',
            price: 15000,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&h=500&fit=crop',
            badge: 'New Arrival',
            rating: 4.8,
            reviewCount: 167,
            stockQuantity: 34,
            isActive: true,
            createdAt: new Date('2024-02-02').toISOString(),
            updatedAt: new Date('2024-02-02').toISOString(),
        },
        {
            categoryId: 6,
            name: 'Hand Sanitizer 500ml',
            slug: 'hand-sanitizer-500ml',
            description: 'Large bottle of alcohol-based hand sanitizer to keep your hands clean on campus. Essential for maintaining hygiene in shared spaces and classrooms.',
            price: 2000,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1584744982493-c4e5d0b0b6c9?w=500&h=500&fit=crop',
            badge: 'Best Value',
            rating: 4.4,
            reviewCount: 201,
            stockQuantity: 95,
            isActive: true,
            createdAt: new Date('2024-01-13').toISOString(),
            updatedAt: new Date('2024-01-13').toISOString(),
        },

        // Food & Snacks (categoryId: 7) - 3 products
        {
            categoryId: 7,
            name: 'Instant Noodles Pack (12-Pack)',
            slug: 'instant-noodles-pack-12-pack',
            description: 'Quick and convenient meals for busy students. Perfect for late-night study sessions or when you need a fast meal between classes.',
            price: 4200,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&h=500&fit=crop',
            badge: 'Best Seller',
            rating: 4.6,
            reviewCount: 256,
            stockQuantity: 73,
            isActive: true,
            createdAt: new Date('2024-01-09').toISOString(),
            updatedAt: new Date('2024-01-09').toISOString(),
        },
        {
            categoryId: 7,
            name: 'Energy Drink 6-Pack',
            slug: 'energy-drink-6-pack',
            description: 'Boost your energy during exam season with these popular energy drinks. Stay alert and focused during long study sessions and early morning classes.',
            price: 3000,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1622543925917-763c34d1a86e?w=500&h=500&fit=crop',
            badge: 'Best Value',
            rating: 4.5,
            reviewCount: 189,
            stockQuantity: 68,
            isActive: true,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            categoryId: 7,
            name: 'Premium Coffee Beans 500g',
            slug: 'premium-coffee-beans-500g',
            description: 'High-quality coffee beans for the ultimate study fuel. Rich flavor and perfect aroma to help you power through assignments and exam preparation.',
            price: 8000,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=500&h=500&fit=crop',
            badge: 'Top Rated',
            rating: 5.0,
            reviewCount: 223,
            stockQuantity: 44,
            isActive: true,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },

        // Accessories (categoryId: 8) - 2 products
        {
            categoryId: 8,
            name: 'Leather Wallet',
            slug: 'leather-wallet',
            description: 'Classic bifold wallet with multiple card slots and bill compartment. Durable genuine leather construction that ages beautifully with use.',
            price: 7500,
            originalPrice: 10000,
            imageUrl: 'https://images.unsplash.com/photo-1627123339143-3aa4d5c0841d?w=500&h=500&fit=crop',
            badge: 'Trending',
            rating: 4.7,
            reviewCount: 145,
            stockQuantity: 51,
            isActive: true,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            categoryId: 8,
            name: 'Sunglasses UV Protection',
            slug: 'sunglasses-uv-protection',
            description: 'Stylish sunglasses with 100% UV protection for sunny campus days. Lightweight frames and polarized lenses reduce glare during outdoor activities.',
            price: 5500,
            originalPrice: null,
            imageUrl: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500&h=500&fit=crop',
            badge: 'New Arrival',
            rating: 4.6,
            reviewCount: 112,
            stockQuantity: 59,
            isActive: true,
            createdAt: new Date('2024-01-31').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
    ];

    await db.insert(products).values(sampleProducts);
    
    console.log('✅ Products seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});