import { db } from '@/db';
import { restaurants } from '@/db/schema';

async function main() {
    const sampleRestaurants = [
        {
            name: 'Jollof Kitchen',
            slug: 'jollof-kitchen',
            description: 'Authentic Nigerian cuisine specializing in perfectly cooked Jollof rice, succulent suya, and rich pepper soup. Experience the true taste of Nigeria with our traditional recipes passed down through generations.',
            imageUrl: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800&h=600&fit=crop',
            rating: 4.8,
            reviewCount: 245,
            deliveryTime: '25-35 min',
            deliveryFee: 50000,
            minimumOrder: 100000,
            cuisine: 'Nigerian',
            isOpen: 1,
            location: 'Lekki Phase 1, Lagos',
            phone: '+234 801 234 5678',
            createdAt: new Date('2024-01-05').toISOString(),
        },
        {
            name: 'Dragon Wok',
            slug: 'dragon-wok',
            description: 'Premium Chinese cuisine featuring authentic stir-fry dishes, dim sum, and noodle specialties. Our expert chefs bring the flavors of the Orient to your doorstep with fresh ingredients and traditional cooking methods.',
            imageUrl: 'https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=800&h=600&fit=crop',
            rating: 4.6,
            reviewCount: 189,
            deliveryTime: '30-40 min',
            deliveryFee: 60000,
            minimumOrder: 150000,
            cuisine: 'Chinese',
            isOpen: 1,
            location: 'Victoria Island, Lagos',
            phone: '+234 802 345 6789',
            createdAt: new Date('2024-01-08').toISOString(),
        },
        {
            name: 'Pizza Paradise',
            slug: 'pizza-paradise',
            description: 'Italian pizzeria serving hand-tossed pizzas with premium toppings and authentic Italian flavors. From classic Margherita to specialty gourmet pizzas, every slice is crafted with passion and quality ingredients.',
            imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&h=600&fit=crop',
            rating: 4.7,
            reviewCount: 312,
            deliveryTime: '20-30 min',
            deliveryFee: 40000,
            minimumOrder: 120000,
            cuisine: 'Italian',
            isOpen: 1,
            location: 'Ikeja GRA, Lagos',
            phone: '+234 803 456 7890',
            createdAt: new Date('2024-01-10').toISOString(),
        },
        {
            name: 'Burger Hub',
            slug: 'burger-hub',
            description: 'American-style fast food restaurant famous for juicy burgers, crispy fries, and loaded milkshakes. Our burgers are made with 100% beef patties and fresh vegetables for that perfect bite every time.',
            imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=600&fit=crop',
            rating: 4.5,
            reviewCount: 276,
            deliveryTime: '15-25 min',
            deliveryFee: 30000,
            minimumOrder: 80000,
            cuisine: 'American',
            isOpen: 1,
            location: 'Surulere, Lagos',
            phone: '+234 804 567 8901',
            createdAt: new Date('2024-01-12').toISOString(),
        },
        {
            name: 'Amala Spot',
            slug: 'amala-spot',
            description: 'Home of the finest Amala, Ewedu, and Gbegiri in Lagos. Our traditional Yoruba dishes are prepared fresh daily with authentic ingredients and served with a variety of premium proteins including assorted meat and fish.',
            imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&h=600&fit=crop',
            rating: 4.9,
            reviewCount: 198,
            deliveryTime: '20-30 min',
            deliveryFee: 45000,
            minimumOrder: 90000,
            cuisine: 'Nigerian',
            isOpen: 1,
            location: 'Yaba, Lagos',
            phone: '+234 805 678 9012',
            createdAt: new Date('2024-01-15').toISOString(),
        },
        {
            name: 'Sushi Delight',
            slug: 'sushi-delight',
            description: 'Premium Japanese restaurant offering fresh sushi rolls, sashimi, and authentic Japanese cuisine. Our skilled sushi chefs prepare each dish with precision using the finest ingredients imported directly from Japan.',
            imageUrl: 'https://images.unsplash.com/photo-1579584425555-c3ce17fd4351?w=800&h=600&fit=crop',
            rating: 4.8,
            reviewCount: 167,
            deliveryTime: '35-45 min',
            deliveryFee: 80000,
            minimumOrder: 200000,
            cuisine: 'Japanese',
            isOpen: 1,
            location: 'Ikoyi, Lagos',
            phone: '+234 806 789 0123',
            createdAt: new Date('2024-01-18').toISOString(),
        },
        {
            name: 'Spice Route',
            slug: 'spice-route',
            description: 'Authentic Indian restaurant specializing in aromatic curries, tandoori dishes, and freshly baked naan. Experience the rich flavors of India with our carefully crafted menu featuring both North and South Indian specialties.',
            imageUrl: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&h=600&fit=crop',
            rating: 4.7,
            reviewCount: 143,
            deliveryTime: '30-40 min',
            deliveryFee: 55000,
            minimumOrder: 130000,
            cuisine: 'Indian',
            isOpen: 1,
            location: 'Ajah, Lagos',
            phone: '+234 807 890 1234',
            createdAt: new Date('2024-01-20').toISOString(),
        },
        {
            name: 'Fried Chicken Express',
            slug: 'fried-chicken-express',
            description: 'Fast food joint serving crispy fried chicken, wings, and chicken tenders with a variety of dipping sauces. Our secret blend of herbs and spices ensures every bite is packed with flavor and crunch.',
            imageUrl: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&h=600&fit=crop',
            rating: 4.4,
            reviewCount: 289,
            deliveryTime: '15-20 min',
            deliveryFee: 25000,
            minimumOrder: 70000,
            cuisine: 'Fast Food',
            isOpen: 1,
            location: 'Maryland, Lagos',
            phone: '+234 808 901 2345',
            createdAt: new Date('2024-01-22').toISOString(),
        },
        {
            name: 'Mama\'s Kitchen',
            slug: 'mamas-kitchen',
            description: 'Home-style Nigerian and Continental meals prepared with love and care. From traditional rice dishes to continental pastas and grills, we serve comfort food that reminds you of home with generous portions and authentic flavors.',
            imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
            rating: 4.6,
            reviewCount: 221,
            deliveryTime: '25-35 min',
            deliveryFee: 50000,
            minimumOrder: 100000,
            cuisine: 'Nigerian',
            isOpen: 1,
            location: 'Gbagada, Lagos',
            phone: '+234 809 012 3456',
            createdAt: new Date('2024-01-25').toISOString(),
        },
        {
            name: 'Shawarma Palace',
            slug: 'shawarma-palace',
            description: 'Middle Eastern cuisine featuring authentic shawarma wraps, falafel, and kebabs. Our shawarmas are loaded with perfectly seasoned meat, fresh vegetables, and our signature sauces wrapped in warm pita bread.',
            imageUrl: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&h=600&fit=crop',
            rating: 4.5,
            reviewCount: 267,
            deliveryTime: '20-30 min',
            deliveryFee: 35000,
            minimumOrder: 80000,
            cuisine: 'Middle Eastern',
            isOpen: 1,
            location: 'Festac, Lagos',
            phone: '+234 810 123 4567',
            createdAt: new Date('2024-01-28').toISOString(),
        },
        {
            name: 'Seafood Bay',
            slug: 'seafood-bay',
            description: 'Premium seafood restaurant offering fresh catches prepared to perfection. From grilled fish and prawns to seafood pasta and platters, we bring the ocean\'s finest to your table with every dish crafted by expert chefs.',
            imageUrl: 'https://images.unsplash.com/photo-1615141982883-c7ad0e69fd62?w=800&h=600&fit=crop',
            rating: 4.7,
            reviewCount: 134,
            deliveryTime: '30-40 min',
            deliveryFee: 70000,
            minimumOrder: 180000,
            cuisine: 'Seafood',
            isOpen: 1,
            location: 'Bar Beach, Lagos',
            phone: '+234 811 234 5678',
            createdAt: new Date('2024-01-30').toISOString(),
        },
        {
            name: 'Vegan Vibes',
            slug: 'vegan-vibes',
            description: 'Plant-based restaurant serving delicious vegan meals, smoothie bowls, and fresh juices. Our menu features creative plant-based alternatives that are both nutritious and flavorful, proving that healthy eating can be incredibly satisfying.',
            imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=600&fit=crop',
            rating: 4.6,
            reviewCount: 156,
            deliveryTime: '25-35 min',
            deliveryFee: 45000,
            minimumOrder: 110000,
            cuisine: 'Vegan',
            isOpen: 1,
            location: 'Banana Island, Lagos',
            phone: '+234 812 345 6789',
            createdAt: new Date('2024-02-02').toISOString(),
        }
    ];

    await db.insert(restaurants).values(sampleRestaurants);
    
    console.log('✅ Restaurants seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});